name: Security Scan

on:
  schedule:
    # Run security scans daily at 2 AM UTC
    - cron: '0 2 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/development.txt
        pip install safety
    
    - name: Run safety check
      run: |
        safety check --json --output safety-report.json || true
        safety check || true
    
    - name: Upload safety report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-scan-report
        path: safety-report.json

  # CodeQL analysis is now handled by GitHub's automatic code scanning
  # The separate CodeQL workflow runs automatically on pushes and PRs

  secret-scan:
    name: Secret Detection
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Run TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        extra_args: --debug --only-verified